env:
  - PROJECT_ID=alpha-eye # Replace with your GCP project ID
  - IMAGE_NAME=alpha-eye-be-v2  # Replace with your desired image name
  - SERVICE_NAME=alpha-eye-cloud-run # Replace with your desired Cloud Run service name
  - REGION=us-central1
  - SECRET_NAME =alpha-eye-be-v2-env
steps:
- name: 'gcr.io/cloud-builders/docker'  # Build Docker image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:v27', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:v27']
# ... (other build steps, if any)

- name: 'gcr.io/cloud-builders/gcloud'  # Deploy to Cloud Run
  args: ['run', 'deploy', '$SERVICE_NAME',
          '--image', 'gcr.io/$PROJECT_ID/$IMAGE_NAME:v27',
          '--platform', 'managed',
          '--region', 'YOUR_REGION',
          '--set-env-vars', 'APP_NAME=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:APP_NAME',
          '--set-env-vars', 'APP_DESCRIPTION=projects/YOUR_PROJECT_ID/secrets/$SECRET_NAME/versions/latest:APP_DESCRIPTION', 
          '--set-env-vars', 'APP_VERSION=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:APP_VERSION',
          '--set-env-vars', 'CONTACT_NAME=projects/YOUR_PROJECT_ID/secrets/$SECRET_NAME/versions/latest:CONTACT_NAME', 
          '--set-env-vars', 'CONTACT_EMAIL=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:CONTACT_EMAIL',
          '--set-env-vars', 'LICENSE_NAME=projects/YOUR_PROJECT_ID/secrets/$SECRET_NAME/versions/latest:LICENSE_NAME', 
          '--set-env-vars', 'POSTGRES_USER=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:POSTGRES_USER',
          '--set-env-vars', 'POSTGRES_PASSWORD=projects/YOUR_PROJECT_ID/secrets/$SECRET_NAME/versions/latest:POSTGRES_PASSWORD', 
          '--set-env-vars', 'POSTGRES_SERVER=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:POSTGRES_SERVER',
          '--set-env-vars', 'POSTGRES_PORT=projects/YOUR_PROJECT_ID/secrets/$SECRET_NAME/versions/latest:POSTGRES_PORT', 
          '--set-env-vars', 'POSTGRES_DB=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:POSTGRES_DB',

          '--set-env-vars', 'PGADMIN_DEFAULT_EMAIL=projects/YOUR_PROJECT_ID/secrets/$SECRET_NAME/versions/latest:PGADMIN_DEFAULT_EMAIL', 
          '--set-env-vars', 'PGADMIN_DEFAULT_PASSWORD=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:PGADMIN_DEFAULT_PASSWORD',
          '--set-env-vars', 'PGADMIN_LISTEN_PORT=projects/YOUR_PROJECT_ID/secrets/$SECRET_NAME/versions/latest:PGADMIN_LISTEN_PORT',

          '--set-env-vars', 'SECRET_KEY=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:SECRET_KEY',
          '--set-env-vars', 'ALGORITHM=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:ALGORITHM',

          '--set-env-vars', 'ACCESS_TOKEN_EXPIRE_MINUTES=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:ACCESS_TOKEN_EXPIRE_MINUTES',
          '--set-env-vars', 'REFRESH_TOKEN_EXPIRE_MINUTES=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REFRESH_TOKEN_EXPIRE_MINUTES',
          '--set-env-vars', 'REFRESH_TOKEN_EXPIRE_DAYS=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REFRESH_TOKEN_EXPIRE_DAYS', 
 
          '--set-env-vars', 'ADMIN_NAME=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:ADMIN_NAME',  
          '--set-env-vars', 'ADMIN_EMAIL=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:ADMIN_EMAIL',
          '--set-env-vars', 'ADMIN_PASSWORD=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:ADMIN_PASSWORD',
          '--set-env-vars', 'ADMIN_USERNAME=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:ADMIN_USERNAME',

          '--set-env-vars', 'REDIS_CACHE_HOST=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REDIS_CACHE_HOST',
          '--set-env-vars', 'REDIS_CACHE_PORT=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REDIS_CACHE_PORT',
          '--set-env-vars', 'REDIS_CACHE_PASSWORD=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REDIS_CACHE_PASSWORD',

          '--set-env-vars', 'CLIENT_CACHE_MAX_AGE=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:CLIENT_CACHE_MAX_AGE',

          '--set-env-vars', 'REDIS_QUEUE_HOST=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REDIS_QUEUE_HOST',

          '--set-env-vars', 'REDIS_QUEUE_PORT=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REDIS_QUEUE_PORT',

          '--set-env-vars', 'TIER_NAME=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:TIER_NAME',

          '--set-env-vars', 'REDIS_RATE_LIMIT_HOST=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REDIS_RATE_LIMIT_HOST',

          '--set-env-vars', 'REDIS_RATE_LIMIT_PORT=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:REDIS_RATE_LIMIT_PORT',

          '--set-env-vars', 'DEFAULT_RATE_LIMIT_LIMIT=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:DEFAULT_RATE_LIMIT_LIMIT',

          '--set-env-vars', 'DEFAULT_RATE_LIMIT_PERIOD=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:DEFAULT_RATE_LIMIT_PERIOD',

          '--set-env-vars', 'TEST_NAME=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:TEST_NAME',

          '--set-env-vars', 'TEST_EMAIL=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:TEST_EMAIL',

          '--set-env-vars', 'TEST_PASSWORD=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:TEST_PASSWORD',

          '--set-env-vars', 'TEST_USERNAME=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:TEST_USERNAME',

          '--set-env-vars', 'CLOUDINARY_CLOUD_NAME=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:CLOUDINARY_CLOUD_NAME',

          '--set-env-vars', 'CLOUDINARY_API_KEY=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:CLOUDINARY_API_KEY',

          '--set-env-vars', 'CLOUDINARY_API_SECRET=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:CLOUDINARY_API_SECRET',  

          '--set-env-vars', 'ENVIRONMENT=projects/$PROJECT_ID/secrets/$SECRET_NAME/versions/latest:ENVIRONMENT',
        ]

